### ISSUE TITLE
Azure ACR: Authorization not recognized after Docker Login

### ISSUE THREAD

**Issue by floriankoch** [kubewarden/kwctl#210] opened 2022-04-28 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is similar to https://github.com/kubewarden/kwctl/issues/208

Push does not works after Docker Login
Push with wasm-to-oci  works

```
kwctl push  annotated-policy.wasm registry://redacted.azurecr.io/polices/test:1
2022-04-28T13:03:04.416833Z  WARN rustls::check: Received a ServerHelloDone handshake message while expecting [CertificateRequest]    
Error: could not push policy: could not push policy: failed to authenticate: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}
```

### Expected Behavior

Push works

### Environment

```markdown
- OS: Linux
- Architecture: amd64
```

**Comment by flavio** [comment] 2022-05-03 09:04
I'm not able to reproduce this issue.

These are the steps I took:

  * Create a new Azure CR
  * Create a service principal to use
    * I took [this script](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal#create-a-service-principal)
    * I changed the `role` (line 20) to be `acrpush`
    * I wrote down the username and password returned by the script
 * I double checked my `~/.docker/config.json` to ensure I didn't have an entry for this freshly created registry
 * I logged into the container registry using the docker cli: `docker login -u <value provided by the script> <fqdn registry>` - once prompted for the password, I entered the one returned by the script
 * I was then able to push a simple container image to the registry using `docker push`
 * I then used the latest release of kwctl: [v0.3.1](https://github.com/kubewarden/kwctl/releases/tag/v0.3.1)
 * I pulled a random policy: `kwctl pull ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11`
 * I then pushed the policy to the remote registry: `kwctl push registry://ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11 <registry>.azurecr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11`
 * I then verified the policy was actually available on the registry using the [`crane`](https://github.com/google/go-containerregistry/tree/main/cmd/crane) tool: `crane manifest <registry>.azurecr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11`

The push took place from my personal computer running Linux on x64_64

**Comment by flavio** [comment] 2022-05-03 09:05
@floriankoch which version of kwctl are you using?

**Comment by flavio** [comment] 2022-05-03 12:24
@kubewarden/kubewarden-developers : moving to "external block" on our project board, waiting for more feedback

**Comment by flavio** [comment] 2022-05-20 12:46
Closing, feel free to reopen with you are still experiencing this issue. As I said, I cannot reproduce that.

**Closed by flavio** 2022-05-20 12:46 UTC
Labels: bug
