### ISSUE TITLE
kwctl outputs info on stderr

### ISSUE THREAD

**Issue by floriankoch** [kubewarden/kwctl#497] opened 2023-05-12 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With kwctl v1.6.0, some info output is printed to stderr, this breaks the e2e tests when checking if e.g. a json patch is correct
 
It does WORK with 1.1.3, because no output is printed to stderr

```
res=$( echo "${output}" | jq -r .patch | base64 -d | jq -r '.[] | select(.path=="/spec/containers/0/env")'.op )
```

```
./kwctl run --disable-wasmtime-cache annotated-policy.wasm -r test_data/pod_no_env.json 
2023-05-12T04:38:20.684656Z  INFO validate_settings{self=PolicyEvaluator { id: "patch-appinsights-env", settings: {} }}:policy_log{self=Policy { id: "patch-appinsights-env", instance_id: Some(1), callback_channel: Some(...) }}: policy_log: validating settings data={}
{"uid":"1299d386-525b-4032-98ae-1949f69f9cfc","allowed":true,"patchType":"JSONPatch","patch":"XXXXXXXX","auditAnnotations":null,"warnings":null}
```

### Expected Behavior

no info is printed to stderr

**Comment by flavio** [comment] 2023-08-04 07:16
Closing since we cannot reproduce it and there was no follow up. Please, reopen if you have more details about it

**Closed by flavio** 2023-08-04 07:16 UTC
