### ISSUE TITLE
kwctl push is failing in v1.17.0

### ISSUE THREAD

**Issue by ferhatguneri** [kubewarden/kwctl#944] opened 2024-10-17 11:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

kwctl push --docker-config-json-path /tmp annotated-policy.wasm registry.com/kubewarden-policies/disallow-automount-default-sa-token-policy:1.11.3
Error: Fail to interact with OCI registry: error sending request for url (https://registry.com/v2/kubewarden-policies/disallow-automount-default-sa-token-policy/blobs/uploads/)

Caused by:
    0: error sending request for url (https://registry.com/v2/kubewarden-policies/disallow-automount-default-sa-token-policy/blobs/uploads/)
    1: client error (Connect)
    2: invalid peer certificate: UnknownIssuer

### Expected Behavior

Policy successfully pushed: registry.com/kubewarden-policies/[disallow-default-namespace-policy](disallow-automount-default-sa-token-policy:1.11.3)@sha256:c40a3fbca4de08ab6942121212121211214dac34d086a

### Steps To Reproduce

Just try to push kubewarden policy with kwctl v1.17.0

### Environment

```markdown
- OS:
- Architecture:
```

### Anything else?

It is working in v1.16.1

**Comment by viccuad** [comment] 2024-10-22 10:58
Hi, I can't reproduce this here with `kwctl` `v1.17`:

```
$ docker pull ghcr.io/viccuad/test/user-group-psp:config-test
config-test: Pulling from viccuad/test/user-group-psp
unsupported media type application/vnd.wasm.config.v1+json
$ kwctl-1.17 pull registry://ghcr.io/viccuad/test/user-group-psp:config-test
$ kwctl-1.17 policies
+-----------------------------------------------------------------------+----------+---------------+--------------+-----------+
| Policy                                                                | Mutating | Context aware | SHA-256      | Size      |
+-----------------------------------------------------------------------+----------+---------------+--------------+-----------+
| registry://ghcr.io/viccuad/test/user-group-psp:config-test            | yes      | no            | f6e0bf76af86 | 1.35 MB   |
+-----------------------------------------------------------------------+----------+---------------+--------------+-----------+
$ kwctl-1.17 push registry://ghcr.io/viccuad/test/user-group-psp:config-test registry://ghcr.io/viccuad/test/user-group-psp:config-test2
Policy successfully pushed: ghcr.io/viccuad/test/user-group-psp@sha256:a11a39b6bc4dc5c047d2d6aa0d33f7208085515d49977ae3c8129fc3706dc9ce
```
(and the new tag `config-test2` was [published](https://github.com/users/viccuad/packages/container/test%2Fuser-group-psp/83434675?tag=config-test2)).


Could you double check that your ~/docker/config.json correctly set up, and the credentials you are using for that repository are working with `crane`, `docker` and so?

**Comment by flavio** [comment] 2024-11-04 14:05
Closing, feel free to reopen the issue if it still persists.

**Closed by flavio** 2024-11-04 14:05 UTC
Labels: kind/bug
