### ISSUE TITLE
`kwctl policies` failed

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kwctl#101] opened 2021-12-30 11:41 UTC
When executed the `kwctl policies` command, it is possible to see the following error:

```console
$ ./target/release/kwctl -V                                                            
kwctl 0.2.4
$ ./target/release/kwctl policies
Error: Bad magic number (at offset 0)
```

This is happening in the main branch as well.

**Comment by nunix** [comment] 2021-12-30 11:55
an additional point from my side: I did remove the `$HOME/.cache/kubewarden` directory and tried to pull again, but got the same error

**Comment by ereslibre** [comment] 2022-01-10 08:09
@jvanz/@nunix can you still reproduce? Can you check that the downloaded policies are WASM modules? I have seen this issue in the past if for example, instead of a WASM module, HTML content was downloaded (due to a GitHub issue), and it tries to be parsed as a WASM module, we end up failing and showing this error.

I think we should improve kwctl so that it checks that the pulled WASM module is a valid one before writing it to the store on disk.

**Comment by flavio** [comment] 2022-01-10 08:12
I second what @ereslibre wrote. To figure it out, just go into the `$HOME/.cache/kubewarden` and then run `file` against each allegedly wasm file you can find in there

**Comment by nunix** [comment] 2022-01-10 08:18
I saw the policy being created but indeed, I didn't performed the `file` against it.

I just tried again, and it worked as intended (with the same version `v0.2.4`)
![image](https://user-images.githubusercontent.com/905874/148735731-eebfb961-0101-40bc-9795-3d9420bbb58c.png)

**Comment by flavio** [comment] 2022-01-10 08:44
Good, we can close this issue and wait for https://github.com/kubewarden/policy-fetcher/issues/15 to be fixed

**Closed by flavio** 2022-01-10 08:44 UTC
